In [1]:
# Importing packages, Pandas, Numpy, RegEx, json
import pandas as pd
import numpy as np
import re

In [2]:
# Sampling data and doing EDA for first 50000 rows to do first parse of dataset

df50k = pd.read_csv('SGJobData.csv', nrows=50000)   # first 50,000 rows only

df50k.shape                    # 50000 rows, 22 columns
df50k.info()                   # Column names and type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   categories                          50000 non-null  object
 1   employmentTypes                     50000 non-null  object
 2   metadata_expiryDate                 50000 non-null  object
 3   metadata_isPostedOnBehalf           50000 non-null  bool
 4   metadata_jobPostId                  50000 non-null  object
 5   metadata_newPostingDate             50000 non-null  object
 6   metadata_originalPostingDate        50000 non-null  object
 7   metadata_repostCount                50000 non-null  int64
 8   metadata_totalNumberJobApplication  50000 non-null  int64
 9   metadata_totalNumberOfView          50000 non-null  int64
 10  minimumYearsExperience              50000 non-null  int64
 11  numberOfVacancies                   50000 non-null  int64
 12  occupationId                        0 non-null      float64
 13  positionLevels                      50000 non-null  object
 14  postedCompany_name                  50000 non-null  object
 15  salary_maximum                      50000 non-null  int64
 16  salary_minimum                      50000 non-null  int64
 17  salary_type                         50000 non-null  object
 18  status_id                           50000 non-null  int64
 19  status_jobStatus                    50000 non-null  object
 20  title                               50000 non-null  object
 21  average_salary                      50000 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 8.1+ MB

In [3]:
# .describe(), include all to show non-numeric columns
df50k.describe(include='all')

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
count,50000,50000,50000,50000,50000,50000,50000,50000.000000,50000.000000,50000.000000,...,0.0,50000,50000,50000.00000,50000.000000,50000,50000.0,50000,50000,50000.000000
unique,3871,8,115,2,50000,95,206,NaN,NaN,NaN,...,NaN,9,11185,NaN,NaN,1,NaN,2,30287,NaN
top,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-04-28,False,MCF-2023-0252866,2023-04-10,2023-03-30,NaN,NaN,NaN,...,NaN,Executive,THE SUPREME HR ADVISORY PTE. LTD.,NaN,NaN,Monthly,NaN,Closed,Sales Executive,NaN
freq,4364,22591,3178,47719,1,3607,3625,NaN,NaN,NaN,...,NaN,12119,4492,NaN,NaN,50000,NaN,46867,188,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.392940,10.872560,134.373720,...,NaN,NaN,NaN,5438.22984,3726.072200,NaN,0.0,NaN,NaN,4582.151020
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.701903,22.582444,177.516308,...,NaN,NaN,NaN,4047.11524,2569.437218,NaN,0.0,NaN,NaN,3232.054418
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,1.00000,1.000000,NaN,0.0,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,40.000000,...,NaN,NaN,NaN,3200.00000,2500.000000,NaN,0.0,NaN,NaN,2850.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,4.000000,78.000000,...,NaN,NaN,NaN,4500.00000,3000.000000,NaN,0.0,NaN,NaN,3750.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,11.000000,161.000000,...,NaN,NaN,NaN,6500.00000,4500.000000,NaN,0.0,NaN,NaN,5400.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,620.000000,5653.000000,...,NaN,NaN,NaN,230000.00000,180000.000000,NaN,0.0,NaN,NaN,205000.000000

In [4]:
df50k.dtypes

# categories labelled object, to check type
# all dates listed, expiryDate, newpostingDate, originalPostingDate labelled object, to check type

categories                             object
employmentTypes                        object
metadata_expiryDate                    object
metadata_isPostedOnBehalf                bool
metadata_jobPostId                     object
metadata_newPostingDate                object
metadata_originalPostingDate           object
metadata_repostCount                    int64
metadata_totalNumberJobApplication      int64
metadata_totalNumberOfView              int64
minimumYearsExperience                  int64
numberOfVacancies                       int64
occupationId                          float64
positionLevels                         object
postedCompany_name                     object
salary_maximum                          int64
salary_minimum                          int64
salary_type                            object
status_id                               int64
status_jobStatus                       object
title                                  object
average_salary                        float64
dtype: object

In [5]:
# Checking 'categories' json dtype, appears as string (str)
type(df50k.loc[0, 'categories'])

str

In [6]:
# Checking 'metadata_expiryDate' type
type(df50k.loc[0, 'metadata_expiryDate'])

str

In [7]:
# Checking 'metadata_newPostingDate' type
type(df50k.loc[0, 'metadata_newPostingDate'])

str

In [8]:
# Checking 'metadata_originalPostingDate' type
type(df50k.loc[0, 'metadata_originalPostingDate'])

str

In [9]:
df50k['salary_maximum'].describe()     
# Picking 'salary_maximum' column
# Median = 4500
# Mean = 5438
# Max = 230000 (Outlier)

count     50000.00000
mean       5438.22984
std        4047.11524
min           1.00000
25%        3200.00000
50%        4500.00000
75%        6500.00000
max      230000.00000
Name: salary_maximum, dtype: float64

In [10]:
df50k['salary_minimum'].describe()
# Picking 'salary_minimum' column
# Median = 3000
# Mean = 3726
# Max = 180000 (outlier)

count     50000.000000
mean       3726.072200
std        2569.437218
min           1.000000
25%        2500.000000
50%        3000.000000
75%        4500.000000
max      180000.000000
Name: salary_minimum, dtype: float64

## 1. From first EDA discovery

### categories:
* _a string formatted in json_

### dates:
* _all dates are in string format and needs to be coverted to date type_

### occupation id:
* _all null, can drop entire column (which we agree to do)_

### salary columns
* _have outliers we need to take into account or set conditionals_

In [11]:
# Using full data csv to account for missing values

df = pd.read_csv('SGJobData.csv')

df.describe(include='all')

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
count,1044597,1044597,1044597,1048585,1044597,1044597,1044597,1.048585e+06,1.048585e+06,1.048585e+06,...,0.0,1044597,1044597,1.048585e+06,1.048585e+06,1044597,1048585.0,1044597,1044597,1.048585e+06
unique,21125,8,453,2,1044597,431,603,NaN,NaN,NaN,...,NaN,9,53151,NaN,NaN,1,NaN,3,377084,NaN
top,"[{""id"":21,""category"":""Information Technology""}]",Permanent,2023-07-28,False,MCF-2023-0252866,2023-06-09,2023-07-14,NaN,NaN,NaN,...,NaN,Executive,THE SUPREME HR ADVISORY PTE. LTD.,NaN,NaN,Monthly,NaN,Open,SUPERVISOR,NaN
freq,92869,458139,4487,986717,1,4508,4029,NaN,NaN,NaN,...,NaN,253701,61638,NaN,NaN,1044597,NaN,902614,8331,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.472327e-02,2.136571e+00,2.674536e+01,...,NaN,NaN,NaN,5.723578e+03,3.815312e+03,NaN,0.0,NaN,NaN,4.769445e+03
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.822675e-01,1.062612e+01,8.262001e+01,...,NaN,NaN,NaN,5.018387e+04,3.172182e+03,NaN,0.0,NaN,NaN,2.547809e+04
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,0.000000e+00,0.000000e+00,NaN,0.0,NaN,NaN,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,1.000000e+00,...,NaN,NaN,NaN,3.300000e+03,2.500000e+03,NaN,0.0,NaN,NaN,2.900000e+03
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,4.000000e+00,...,NaN,NaN,NaN,4.500000e+03,3.000000e+03,NaN,0.0,NaN,NaN,3.800000e+03
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,1.000000e+00,1.700000e+01,...,NaN,NaN,NaN,6.500000e+03,4.500000e+03,NaN,0.0,NaN,NaN,5.500000e+03
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+00,1.342000e+03,8.190000e+03,...,NaN,NaN,NaN,2.533000e+07,3.500000e+05,NaN,0.0,NaN,NaN,1.266640e+07

Salary minimum in full data set has a $0 salary
Salary maximum in full data set has a $25,330,000 salary

# MISSING VALUES

In [12]:
# Missing Values

missing_values = df.isna().sum()

print(missing_values[missing_values > 0].sort_values(ascending=False))

occupationId                    1048585
categories                         3988
employmentTypes                    3988
metadata_expiryDate                3988
metadata_jobPostId                 3988
metadata_newPostingDate            3988
metadata_originalPostingDate       3988
positionLevels                     3988
postedCompany_name                 3988
salary_type                        3988
status_jobStatus                   3988
title                              3988
dtype: int64

* _12 Columns with missing values_
* _11 Columns, if we drop occupation id column_
* _To decide which column is important to our business plan/story_

# DUPLICATES

In [13]:
# Checking for Duplicates

df.duplicated().sum()
#returns 3987

df.duplicated(subset='metadata_jobPostId', keep = False).sum()
#returns 3988
# Jobpost ID should be unique 

df['metadata_jobPostId'].isna().sum()
#returns 3988
#These jobpost ID entries may not be duplicates, they are Null 

# Check within the subset, how many duplicates
mask1 = df[df.duplicated(subset='metadata_jobPostId', keep=False)]
# print(sub)
mask1.isna().sum(axis=1) #within each row, 12 are null
mask1.isna().sum(axis=1).value_counts() #returns 3988

# Comparing to the above missing value portion, these 3988 entries are all null
# Therefore we should drop these rows

12    3988
dtype: int64

In [14]:
# Finding real duplicates

# Adding columns that can flag out duplicates
# Posts with similar company name, title, salary minimum and maximum
mask2 = df.duplicated(subset=['postedCompany_name', 'title', 'salary_maximum', 'salary_minimum', 'employmentTypes'])
mask2.sum()
df[mask2]

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,occupationId,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
387,"[{""id"":11,""category"":""Engineering""},{""id"":25,""...",Permanent,2023-05-05,False,MCF-2023-0274311,2023-04-28,2023-04-08,2,8,115,...,NaN,Fresh/entry level,ATOMRECRUIT PTE. LTD.,3300,2900,Monthly,0,Closed,"Service Engineer (Fresh/No experience welcome,...",3100.0
511,"[{""id"":1,""category"":""Accounting / Auditing / T...",Permanent,2023-04-15,False,MCF-2023-0274094,2023-04-08,2023-04-08,0,1,36,...,NaN,Junior Executive,RECRUITPEDIA PTE. LTD.,2400,1800,Monthly,0,Closed,Admin & Accounts Assistant (Medical MNC),2100.0
633,"[{""id"":21,""category"":""Information Technology""}]",Contract,2023-04-22,False,MCF-2023-0274430,2023-04-08,2023-04-08,0,0,51,...,NaN,Senior Executive,QUANTUM INFOTECH SOLUTIONS PTE. LTD.,9000,7000,Monthly,0,Closed,Senior Software Engineer,8000.0
697,"[{""id"":2,""category"":""Admin / Secretarial""},{""i...",Contract,2023-05-08,False,MCF-2023-0274578,2023-04-08,2023-04-08,0,2,59,...,NaN,Fresh/entry level,MINDFLEX EDUCATION PTE. LTD.,1200,1000,Monthly,0,Closed,Operations & Marketing Intern (FUN Environment),1100.0
699,"[{""id"":24,""category"":""Logistics / Supply Chain""}]",Temporary,2023-05-08,False,MCF-2023-0274531,2023-04-08,2023-04-08,0,2,28,...,NaN,Senior Executive,RECRUITPEDIA PTE. LTD.,5000,4500,Monthly,0,Closed,Buyer / 1 Year Contract / Oil & Gas MNC / Project,4750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048567,"[{""id"":8,""category"":""Customer Service""},{""id"":...",Full Time,2024-06-28,False,MCF-2024-0783858,2024-05-29,2024-05-29,0,0,0,...,NaN,Junior Executive,RECRUITPEDIA PTE. LTD.,3200,2600,Monthly,0,Open,Customer Service Administrator / Global MNC / ...,2900.0
1048568,"[{""id"":2,""category"":""Admin / Secretarial""},{""i...",Contract,2024-06-28,False,MCF-2024-0783863,2024-05-29,2024-05-29,0,0,2,...,NaN,Junior Executive,THE INCEPTION RECRUITMENT PTE. LTD.,3500,2800,Monthly,0,Open,IT and Facilities Support,3150.0
1048571,"[{""id"":24,""category"":""Logistics / Supply Chain...",Temporary,2024-06-05,False,MCF-2024-0783839,2024-05-29,2024-05-29,0,0,0,...,NaN,Executive,RECRUITPEDIA PTE. LTD.,5000,3500,Monthly,0,Open,Supply Chain Coordinator (6 Months Contract) /...,4250.0
1048573,"[{""id"":35,""category"":""Sales / Retail""}]",Full Time,2024-06-28,False,MCF-2024-0783852,2024-05-29,2024-05-29,0,0,0,...,NaN,Executive,RECRUITPEDIA PTE. LTD.,3000,2500,Monthly,0,Open,Senior Sales Associate / Central / jewelry and...,2750.0
1048574,"[{""id"":11,""category"":""Engineering""},{""id"":18,""...",Full Time,2024-06-28,False,MCF-2024-0783866,2024-05-29,2024-05-29,0,0,0,...,NaN,Senior Executive,RECRUITPEDIA PTE. LTD.,8500,6000,Monthly,0,Open,"Senior Energy Engineer (SCEM) - West, Global MNC",7250.0

#### Missing values 
* _11 columns (excluding occupation id) with 3988 missing values_
#### Duplicate rows
*  
#### Wrong data types
* 
#### Impossible values 
* _0 salary or 23550000 salary_